name: Get YouTube Comments

on:
  schedule:
    - cron: '0 3 * * 1'  # 每周一UTC時間上午3時（日本標準時間中午12時）
  push:
    paths:
      - 'main/readme.md'

jobs:
  get-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

    - name: Run getcomment script
      run: python backend/getcomment.py
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
