name: Get YouTube Comments

on:
  schedule:
    - cron: '0 3 * * 1'  # 每周一UTC時間上午3時（日本標準時間中午12時）
  push:
    paths:
      - 'README.md'

jobs:
  get-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

    - name: Run getcomment script
      run: python backend/getcomment.py
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    - name: Check for changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add timeline/
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m 'Add new comments to timeline'
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
