name: Update Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at UTC 00:00

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Set up Git config
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Run the script to update data
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: |
        python backend/getsheet.py  # Use the correct path

    - name: Check for changes
      id: check_for_changes
      run: |
        git add data.json
        if git diff-index --quiet HEAD; then
          echo "::set-output name=changes::No"
        else
          echo "::set-output name=changes::Yes"
        fi

    - name: Commit and push changes
      if: steps.check_for_changes.outputs.changes == 'Yes'
      run: |
        git commit -m "Update data.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
