name: Update Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # 每週日的 UTC 時間 00:00 運行

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git config
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Run the script to update data
      run: |
        python getsheet.py

    - name: Check for changes
      id: check_for_changes
      run: |
        git add data.json
        if git diff-index --quiet HEAD; then
          echo "::set-output name=changes::No"
        else
          echo "::set-output name=changes::Yes"

    - name: Commit and push changes
      if: steps.check_for_changes.outputs.changes == 'Yes'
      run: |
        git commit -m "Update data.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
