name: Update Database

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client google-api-python-client

    - name: Create credentials file
      run: |
        echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" > credentials.json

    - name: Update SQLite DB
      run: |
        python app.py
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

    - name: Commit and push changes
      run: |
        git config user.email "${{ secrets.USER_EMAIL }}"
        git config user.name "${{ secrets.USER_NAME }}"
        git add backend/mydatabase.db
        git commit -m "Update database"
        git push https://HoshiMin-db:${{ secrets.PAT_TOKEN }}@github.com/HoshiMin-db/HoshiHo_SongList
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
